/**
 * Everything this app is built from, and what each piece is licensed under.
 *
 * Two sources, because there are two kinds of dependency and only one of them can be discovered
 * automatically. The npm tree is generated by scripts/generate-attributions.mjs, which reads what
 * actually ships rather than what someone remembered to write down. Native components are listed
 * here by hand: sherpa-onnx, espeak-ng, ffmpeg and the rest arrive through Gradle or a build
 * script, so nothing can enumerate them from a package manifest.
 *
 * A hand-maintained list is the part that rots, so this one carries its own honesty flag. Where a
 * licence has not actually been confirmed against the shipped artefact it says so, and the screen
 * shows that rather than a confident guess. An attribution list that quietly invents licences is
 * worse than none, because it looks like the question was settled.
 */

export interface AttributedPackage {
  name: string;
  version: string;
  license: string;
  repository?: string;
}

export interface AttributionData {
  packageCount: number;
  packages: AttributedPackage[];
  licenseTexts: Record<string, string>;
  notices: Record<string, string>;
}

export interface NativeComponent {
  name: string;
  license: string;
  /** What it does here, in a sentence someone who did not write the build can follow. */
  role: string;
  url: string;
  /**
   * False when the licence above has not been checked against the artefact that actually ships.
   * Shown in the app, because an unverified claim presented as fact is the failure this list is
   * meant to prevent.
   */
  verified: boolean;
  /** Which builds contain it. Cast ships only in the Play build; the F-Droid build omits it. */
  flavour?: 'gplay' | 'foss' | 'both';
  note?: string;
}

/**
 * Native and vendored components, in rough order of how much of the app they are.
 *
 * Kept deliberately short. This is not every transitive Android library — AndroidX alone would run
 * to hundreds — but the components that are large, that carry copyleft terms, or that someone
 * reading this would want to know were in here.
 */
export const NATIVE_COMPONENTS: NativeComponent[] = [
  {
    name: 'sherpa-onnx',
    license: 'Apache-2.0',
    role: 'Runs the neural voice that reads documents and books aloud. Compiled from pinned source rather than shipped as a binary.',
    url: 'https://github.com/k2-fsa/sherpa-onnx',
    verified: true,
    flavour: 'both',
  },
  {
    name: 'ONNX Runtime',
    license: 'MIT',
    role: 'The inference engine sherpa-onnx runs the voice model on.',
    url: 'https://github.com/microsoft/onnxruntime',
    verified: true,
    flavour: 'both',
  },
  {
    name: 'espeak-ng',
    license: 'GPL-3.0-or-later',
    role: 'Turns text into the phonemes the voice model speaks. Only the English pronunciation data is included.',
    url: 'https://github.com/espeak-ng/espeak-ng',
    verified: true,
    flavour: 'both',
  },
  {
    name: 'Piper voice: en_GB-alan-medium',
    license: 'Unresolved',
    role: 'The voice itself. Trained from the mimic3 apope dataset.',
    url: 'https://github.com/MycroftAI/mimic3-voices/blob/master/voices/en_UK/apope_low',
    verified: false,
    flavour: 'both',
    note: 'The model card that ships with the voice states only "License: See URL" and does not name one. This needs resolving against the dataset before release.',
  },
  {
    name: 'youtubedl-android',
    license: 'GPL-3.0',
    role: 'Fetches audio from the web. Bundles its own Python and ffmpeg binaries, which are most of the app download size.',
    url: 'https://github.com/junkfood02/youtubedl-android',
    verified: true,
    flavour: 'both',
  },
  {
    name: 'ffmpeg',
    license: 'LGPL-2.1-or-later, or GPL-2.0-or-later',
    role: 'Audio conversion, bundled inside youtubedl-android.',
    url: 'https://ffmpeg.org',
    verified: false,
    flavour: 'both',
    note: 'Which of the two applies depends on the flags it was compiled with upstream, and that has not been checked against the binary that ships.',
  },
  {
    name: 'Python',
    license: 'PSF-2.0',
    role: 'Runs yt-dlp, bundled inside youtubedl-android.',
    url: 'https://www.python.org',
    verified: true,
    flavour: 'both',
  },
  {
    name: 'Capacitor',
    license: 'MIT',
    role: 'Carries the app into a native Android shell and bridges to the plugins.',
    url: 'https://github.com/ionic-team/capacitor',
    verified: true,
    flavour: 'both',
  },
  {
    name: 'AndroidX, including Media3 and ExoPlayer',
    license: 'Apache-2.0',
    role: 'Playback, the media session behind the lock screen controls, and the interface toolkit.',
    url: 'https://developer.android.com/jetpack/androidx',
    verified: true,
    flavour: 'both',
  },
  {
    name: 'Google Cast SDK',
    license: 'Proprietary',
    role: 'Casting to Chromecast, in the Play Store build only.',
    url: 'https://developers.google.com/cast',
    verified: true,
    flavour: 'gplay',
    note: 'Not free software, which is why the F-Droid build leaves it out. That build casts through Sandbox Server instead.',
  },
  {
    name: 'foliate-js',
    license: 'MIT',
    role: 'Reads EPUB and Kindle files so they can be opened and narrated.',
    url: 'https://github.com/johnfactotum/foliate-js',
    verified: true,
    flavour: 'both',
  },
];

/**
 * Load the generated npm list.
 *
 * Imported on demand because it is about a hundred kilobytes of licence text that almost nobody
 * opens. A static import would put all of it in the startup path of a phone app whose first screen
 * is a music library, for a screen most people will never visit.
 */
export async function loadAttributions(): Promise<AttributionData> {
  const data = await import('./generated/attributions.json');
  return (data.default ?? data) as unknown as AttributionData;
}

export interface LicenceGroup {
  license: string;
  packages: AttributedPackage[];
}

/**
 * Group packages by licence, commonest first.
 *
 * Four hundred names in one alphabetical column tells a reader nothing. Grouped, the shape of the
 * answer is visible immediately: overwhelmingly MIT, a handful of Apache, and then the few worth
 * actually looking at.
 */
export function groupByLicence(packages: AttributedPackage[]): LicenceGroup[] {
  const groups = new Map<string, AttributedPackage[]>();
  for (const pkg of packages) {
    const key = pkg.license || 'UNKNOWN';
    if (!groups.has(key)) groups.set(key, []);
    groups.get(key)!.push(pkg);
  }
  return [...groups.entries()]
    .map(([license, list]) => ({
      license,
      packages: [...list].sort((a, b) => a.name.localeCompare(b.name)),
    }))
    .sort((a, b) => b.packages.length - a.packages.length || a.license.localeCompare(b.license));
}

/**
 * Components whose licence is not actually settled.
 *
 * Surfaced rather than buried. These are the entries that need a person to go and check something,
 * and a list that hides them is a list that will still be wrong next year.
 */
export function unresolvedComponents(
  components: NativeComponent[] = NATIVE_COMPONENTS,
): NativeComponent[] {
  return components.filter((component) => !component.verified);
}

/** Packages that declare no licence at all, which is a different problem from an unusual one. */
export function undeclaredPackages(packages: AttributedPackage[]): AttributedPackage[] {
  return packages.filter((pkg) => !pkg.license || pkg.license === 'UNKNOWN');
}
